### ISSUE TITLE
Windows build support

### ISSUE THREAD

**Issue by markasoftware** [markasoftware/SpecDB#13]
Add support for building on Windows so it is easier for the filthy Windows users to contribute, as fucked up as that may sound. Main thing that needs to be done is a batch equivalent of `build/build.bash`. Looked into batsh but doesn't seem sufficient (no way to get command line args, no redirection, etc).

**Comment by rakshithravi1997** [comment]
Should a simple `npm install` followed by a `npm run build` just work? After all, its just node right? Unless there's something I'm just not seeing

**Comment by markasoftware** [comment]
Hey @rakshithravi1997, `npm run build` runs a bash script (see `build/build.bash`), which is not node.

**Comment by zcskywire2** [comment]
With the summer anniversary update to windows 10 you can now build the project straight in windows. This can be achieved by installing the Linux Ubuntu system extension and then setting up the required dependencies.Then one can use the Linux terminal straight from the windows terminal to build the project. Currently using it to test additions to the database and it works well.

**Comment by markasoftware** [comment]
Fixed in c7c42a87218018b259ecf722b699dfb18ee2b235
