### ISSUE TITLE
Ryzen 3 1200 and 1300x Specifications

### ISSUE THREAD

**Issue by JackStillAlive** [markasoftware/SpecDB#15]
Added confirmed specifications for Ryzen3 1200 and 1300x alongside a "base" file for the Ryzen 3 Lineup

[R31200+1300x.zip](https://github.com/markasoftware/SpecDB/files/1166557/R31200.1300x.zip)

**Comment by zcskywire2** [comment]
I took the files you wrote up, checked that they worked and implemented them in my fork. They are contained in the pull request I just made.

**Comment by markasoftware** [comment]
Will be implementing these based on the ones in @zcskywire2 's fork. Thanks @JackStillAlive for creating these!
