### ISSUE TITLE
Setting xfr support or unlocked to false outside of the base CPU yaml file breaks the application page

### ISSUE THREAD

**Issue by zcskywire2** [markasoftware/SpecDB#16]
When using a inherited yaml file to set these methods to false the interface of the application misbehaves.  Ex Ryzen-inherit. These actions include: Breaking the advance settings tab so that clicking on it does nothing, failing to refresh the applications compare page, preventing the user from navigating the application. Loading a properly functioning CPU into compare negates the issues caused by this until it is removed. This at the moment can be bypassed by setting those settings directly in the cpu's yaml file. Ex R5 1600X

**Comment by markasoftware** [comment]
Generally speaking it's recommended to omit unlocked or XFR support if you don't have them, they will be automatically filled in as false. But yes, this is a still a bug, and I will look into it soon.
