### ISSUE TITLE
Neglecting to set Boost Frequency: for CPUsbreaks the application

### ISSUE THREAD

**Issue by zcskywire2** [markasoftware/SpecDB#19]
While yes this seems quite obvious as leaving any field null is bound to cause issues, leaving this field undefined causes the application to misbehave in the same ways as #16. This becomes an issue when you have CPU's that do not have turbo boost. Simply setting Boost Frequency: N/A resolves the issue, however this certainly not the best solution. Perhaps a Boolean variable for turbo mode much like the one for XFR 
support would be a more proper solution?

**Comment by markasoftware** [comment]
Okay, the reason this occurs is because the `Boost Frequency` is used to generate the part's "subtext", the stuff that displays in grey below the part name when selecting it, for example:

```
16 Cores, 32 Threads
3.4GHz Base, 4.0GHz Boost
180W TDP
```

I'll update this to make the boost optional.
