### ISSUE TITLE
APU support

### ISSUE THREAD

**Issue by markasoftware** [markasoftware/SpecDB#23]

**Comment by zcskywire2** [comment]
I saw that the start for support was there, give me some ideas for what information the yamls would need ( probably just everything in GPU + CPU) and I'll start producing some of those families as well.

**Comment by markasoftware** [comment]
I'm honestly not super familiar with APUs, having never used them and not being particularly interested in them, so use your best judgement to make a few, then I'll look over it and see what needs to be changed. It will require some special treatment because I want it to be possible to compare APUs with CPUs side-by-side, but currently you can't compare different types of parts. It's probably best to get GPU stuff first since it's ready, and I can get APU stuff working in the meantime.

**Comment by markasoftware** [comment]
APUs support has been added, and most/all recent APUs have been added by @zcskywire2
