### ISSUE TITLE
Threaripper listed under wrong socket

### ISSUE THREAD

**Issue by kunamashina** [markasoftware/SpecDB#28]
Threaripper processors should be in separate group based on its TR4 socket and not in Ryzen group with AM4 socket as listed on the site :)

**Comment by markasoftware** [comment]
It is not supposed to be organized by socket, it's sort of organized by series/lineup to some extent.

**Comment by kunamashina** [comment]
Understood now, I am adding all athlon CPUs with the latest 7th generation APUs + CPUs from Excavator architecture. I hope you will include them after I send you the files :)

**Comment by markasoftware** [comment]
Hey, I really appreciate the attitude, but before putting in too much work, I'd highly recommend you check out the repo @zcskywire2 made and make sure he hasn't already done it: https://github.com/zcskywire2/SpecDB. If you're planning to contribute, please fork the repo, modify files there, then make a pull request. Thanks!

**Comment by zcskywire2** [comment]
I have done all the non apu athlons up to kaveri(Athlon X4 880K and earlier). May do the Carrizo and Bristol Ridge ones soon but if your interested feel free too. I've also learned the quirks of the yamls pretty well if you need help or guidance.

**Comment by zcskywire2** [comment]
I should also state that Apu's are not yet supported

**Comment by zcskywire2** [comment]
Also if you don't feel like forking just drop me the files and I get them added in

**Comment by markasoftware** [comment]
There's also a wiki nobody seems to know about...https://github.com/markasoftware/SpecDB/wiki

It has all the information about building the project, how the yamls work, and the basic spec-creation tools (although it may be easier to just write the yamls by hand, the tools aren't very good).

**Comment by markasoftware** [comment]
Not related to this thread, but because of these kinds of extended discussions in issues, PR, and commit threads, I've created a [gitter room](https://gitter.im/SpecDB-AMD/SpecDB) for SpecDB, where discussions which aren't directly related to an issue, commit, or pull request can go.

**Comment by kunamashina** [comment]
Expecting Zack in the [gitter room](https://gitter.im/SpecDB-AMD/SpecDB)

**Comment by markasoftware** [comment]
Now using a [discord](https://discord.gg/xfVHZAb), for anybody who stumbles upon this thread.
