### ISSUE TITLE
Table cannot be swiped left or right on mobile

### ISSUE THREAD

**Issue by zcskywire2** [markasoftware/SpecDB#34]
With the table update on the beta branch you cannot slide it left or right to view all the components in compare. This leaves most of them cutoff and unviewable. May also affect the desktop version. Also the old table buttons are there and do nothing ATM.

**Comment by markasoftware** [comment]
Mobile issues for table update will be covered in #25. Will keep this open to track the button issues.

**Comment by zcskywire2** [comment]
Checking it out on desktop, there is no way to scroll the table either. It's just not typically shown  because of the higher resolution and wider aspect ratio

**Comment by markasoftware** [comment]
Table can now be swiped as of d0bd41da06f79876cabc2cde654fd8f60176686d
