### ISSUE TITLE
Vulkan 1.1

### ISSUE THREAD

**Issue by StandaSK** [markasoftware/SpecDB#57]
The latest AMD driver makes (all of the GCN GPUs, i believe) conformant with Vulkan 1.1

https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Adrenalin-Edition-18.3.3-Release-Notes.aspx

**Comment by markasoftware** [comment]
Is this also for APUs, or just GPUs?

**Comment by StandaSK** [comment]
Right now it seems it's only for GPUs, but considering Vulkan 1.1 is just Vulkan 1.0, only with some extensions now being mandatory instead of optional, there's nothing really stopping the APUs from being compliant as well.

**Comment by markasoftware** [comment]
new policy is to close bugs that are fixed in beta
