### ISSUE TITLE
(Beta) Show all matches in search breaks the site.

### ISSUE THREAD

**Issue by zcskywire2** [markasoftware/SpecDB#64]
When using the search function on the beta site, if show all results is clicked the site fails to update until reloaded. These issues include, failure to update comparison after the first part selected, failure to update search, failure to show search subcategories , and failure to exit search. The url is updated how ever with the new url, but is never loaded.
![image](https://user-images.githubusercontent.com/4808017/52299974-c627ce80-2954-11e9-9be3-35767ce54f56.png)

**Comment by zcskywire2** [comment]
Works on correctly on the live version of the master branch

**Comment by markasoftware** [comment]
Fixed with 81f24b05cb7cd28e917d141b5229149f3e1a39d0
